# Generated by Django 2.0.9 on 2018-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180805_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_from_app',
            field=models.BooleanField(default=True, help_text='Contact added from application.'),
        ),
    ]
