# Generated by Django 2.0.9 on 2018-10-18 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_contact_is_from_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='holder',
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_from_app',
            field=models.BooleanField(default=False, help_text='Contact added from application.'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='display_name',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('holder', 'contact')},
        ),
    ]
