# Generated by Django 2.0.9 on 2018-10-18 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_auto_20181018_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('holder', 'user')},
        ),
    ]
