# Generated by Django 2.0.9 on 2018-11-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20181018_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_blocked',
        ),
    ]
