# Generated by Django 2.0.7 on 2018-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180709_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None, help_text='Birtht data', null=True),
        ),
    ]
