# Generated by Django 2.1 on 2018-08-05 12:31

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.utils.gen_smscode, editable=False, help_text='Code from SMS.', max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('sended', models.DateTimeField(auto_now_add=True, help_text='SMS sending time.')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_code', to='users.SMSCode'),
        ),
    ]
