# Generated by Django 2.0.8 on 2018-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180805_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_self_registration',
            field=models.BooleanField(default=True, help_text='The user came to the service and registered himself.'),
        ),
    ]
