# Generated by Django 2.0.8 on 2018-09-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180813_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_self_registration',
        ),
    ]
