# Generated by Django 2.0.8 on 2018-09-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180912_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
