# Generated by Django 2.0.8 on 2018-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180927_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
