# Generated by Django 2.0.9 on 2018-10-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20181011_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatar_uuid',
        ),
    ]
