# Generated by Django 2.0.9 on 2018-11-15 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20181022_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_blocked',
            new_name='is_restricted',
        ),
        migrations.AddField(
            model_name='user',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='_user_black_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
