# Generated by Django 2.0.9 on 2018-12-06 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181115_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='black_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
