# Generated by Django 2.1.4 on 2018-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20181206_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Valid Values: M or F', max_length=1),
        ),
    ]
