# Generated by Django 2.0.8 on 2018-08-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created_at',)},
        ),
    ]
