FROM alpine:edge

ARG BUILD_DATE
ARG VCS_REF

LABEL maintainer="oc@co.ru" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="Limon Public API" \
    org.label-schema.url="https://oraaange.herokuapp.com" \
    org.label-schema.vcs-url="https://gitlab.limonapp.com/docker/base.git" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.docker.cmd="docker run -d --rm --publish 8000:8000 --name limon registry.limonapp.com/limon/base" \
    org.label-schema.schema-version="1.0"

#ENV SSH_PRIVATE_KEY=""

WORKDIR /app
COPY . /app

# Dependicies
RUN apk add --no-cache make openssh-client python3 python3-dev postgresql-client postgresql-dev docker && \
    pip3 install --upgrade pipenv
