# Generated by Django 2.0.8 on 2018-08-14 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuses', '0002_auto_20180709_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='adabuse',
            name='is_confirmed',
            field=models.NullBooleanField(help_text='Is abuse confirmed'),
        ),
        migrations.AddField(
            model_name='userabuse',
            name='is_confirmed',
            field=models.NullBooleanField(help_text='Is abuse confirmed'),
        ),
        migrations.AlterField(
            model_name='adabuse',
            name='ad',
            field=models.ForeignKey(help_text='On ad', on_delete=django.db.models.deletion.CASCADE, to='ads.Ad'),
        ),
        migrations.AlterField(
            model_name='adabuse',
            name='comment',
            field=models.CharField(blank=True, help_text='Abuse comment', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='adabuse',
            name='reason',
            field=models.CharField(choices=[('ADVERTISING', 'Advertising'), ('UNCENSORED_CONTENT', 'Uncensored content')], help_text='Abuse reason', max_length=32),
        ),
        migrations.AlterField(
            model_name='adabuse',
            name='sender',
            field=models.ForeignKey(help_text='Abuse sender', on_delete=django.db.models.deletion.CASCADE, related_name='adabuses_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userabuse',
            name='comment',
            field=models.CharField(blank=True, help_text='Abuse comment', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userabuse',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('BAD_BEHAVIOR', 'Bad behavior'), ('FRAUD', 'Fraud'), ('UNCENSORED_CONTENT', 'Uncensored content')], help_text='Abuse reason', max_length=32),
        ),
        migrations.AlterField(
            model_name='userabuse',
            name='sender',
            field=models.ForeignKey(help_text='Abuse sender', on_delete=django.db.models.deletion.CASCADE, related_name='userabuses_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userabuse',
            name='user',
            field=models.ForeignKey(help_text='On user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
