# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 06:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of object.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=1)),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
