# Generated by Django 2.0.8 on 2018-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20180712_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Is blocked by moderator'),
        ),
    ]
