# Generated by Django 2.0.8 on 2018-08-28 13:52

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20180822_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=(datetime.datetime(2018, 8, 28, 13, 52, 2, 762640, tzinfo=utc), None), help_text='Ad period'),
        ),
    ]
