# Generated by Django 2.0.8 on 2018-09-05 09:59

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20180828_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=(datetime.datetime(2018, 9, 5, 9, 58, 43, 182115, tzinfo=utc), None), help_text='Ad period'),
        ),
    ]
