# Generated by Django 2.0.8 on 2018-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20180905_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('DATING', 'Dating'), ('MEETING', 'Meeting'), ('TRAVEL', 'Travel')], help_text='Ad type.', max_length=16),
        ),
    ]
