# Generated by Django 2.0.8 on 2018-09-20 08:09

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20180915_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=(datetime.datetime(2018, 9, 20, 8, 9, 33, 938814), None), help_text='Ad period'),
        ),
    ]
