# Generated by Django 2.0.9 on 2018-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20181115_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='Ad title', help_text='Title', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(help_text='Ad description'),
        ),
    ]
