# Generated by Django 2.1.4 on 2018-12-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20181128_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='Valid values: M, F, N', max_length=1),
        ),
    ]
