# Generated by Django 2.1.4 on 2018-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20181211_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], help_text='Valid values: M, F, N', max_length=1),
        ),
    ]
