# Generated by Django 2.1.4 on 2019-01-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_ad_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-created_at',)},
        ),
    ]
