# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of object.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('size', models.PositiveIntegerField()),
                ('type', models.CharField(default='application/octet-stream', max_length=50)),
                ('url', models.URLField(null=True)),
                ('preview', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
