# Generated by Django 2.0.8 on 2018-09-12 13:30

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='File object.', null=True, upload_to=files.models.rename_to_uuid),
        ),
    ]
