# Generated by Django 2.0.8 on 2018-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180912_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='preview',
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=32, null=True),
        ),
    ]
