# Generated by Django 2.0.9 on 2018-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20180915_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
