# Generated by Django 2.0.9 on 2018-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_is_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
