# Generated by Django 2.0.9 on 2018-10-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='handler',
            field=models.CharField(choices=[('avatar', 'Avatar')], default=None, max_length=6, null=True),
        ),
    ]
