# Generated by Django 2.1.4 on 2019-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('speech', 'Speech'), ('document', 'Document')], default='document', help_text='Valid values: image, video, audio and document.', max_length=9),
        ),
        migrations.AlterField(
            model_name='file',
            name='handler',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('audio_enc', 'Audio Encoding'), ('video_enc', 'Video Encoding')], default=None, max_length=6, null=True),
        ),
    ]
