# Generated by Django 2.1.4 on 2019-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20190117_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='handler',
            field=models.CharField(choices=[('none', 'None'), ('avatar', 'Avatar'), ('audio_enc', 'Audio Encoding'), ('video_enc', 'Video Encoding')], default=None, max_length=6, null=True),
        ),
    ]
