# Generated by Django 2.1.5 on 2019-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20190127_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('speech', 'Speech'), ('document', 'Document'), ('portfolio', 'Portfolio')], default='document', help_text='Valid values: image, video, audio and document.', max_length=9),
        ),
    ]
