# Generated by Django 2.1.5 on 2019-02-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20190129_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
