# Generated by Django 2.1.5 on 2019-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=256, null=True),
        ),
    ]
