# Generated by Django 2.1.7 on 2019-04-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20190227_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('speech', 'Speech'), ('document', 'Document'), ('portfolio', 'Portfolio'), ('avatar', 'Avatar')], default='document', help_text='Valid values: image, video, audio and document.', max_length=9),
        ),
    ]
