on: [push, pull_request]

name: Tests

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9.5
          architecture: x64
      - uses: huaxk/postgis-action@v1
        with:
          postgresql user: test
          postgresql password: justfortest
          postgresql db: testdb
      - uses: dschep/install-pipenv-action@v1
      - run: pipenv install
      - run: pipenv --venv
      - name: Install GDAL
        run: sudo apt-get install python3-gdal
      - run: pipenv run pytest
        env:
          DATABASE_URL: postgres://test:justfortest@localhost:5432/testdb
          SECRET_KEY: justfortests0123456789
          AWS_ACCESS_KEY_ID: Q3AM3UQ867SPQQA43P2F
          AWS_SECRET_ACCESS_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
          AWS_STORAGE_BUCKET_NAME: oraaange-files
          AWS_AUTO_CREATE_BUCKET: True
          AWS_S3_ENDPOINT_URL: https://play.min.io:9000

